crypto:
  jwt_secret: jwt_secret
  google_client_id: testclientid
database:
  kind: sqlite
  generate_schemas: true
  sqlite:
    host: ":memory:"
email:
  host: localhost
  port: 587
  name: Ben from DPSH
  email: email
  password: password
file:
  fs_type: file
  audio:
    min_duration: 0.0
site:
  homepage: http://localhost:3000
user:
  admin_emails:
    - "ben@dpsh.dev"
worker:
  host: localhost
  port: 8080
  sampling_timesteps: 5
