database:
  kind: postgres
  postgres:
    write_endpoint:
      host: ${oc.env:DB_WRITE_HOST}
      port: ${oc.decode:${oc.env:DB_PORT,5432}}
      username: ${oc.env:DB_USERNAME}
      password: ${oc.env:DB_PASSWORD}
    read_endpoint:
      host: ${oc.env:DB_READ_HOST}
      port: ${database.postgres.write_endpoint.port}
      username: ${database.postgres.write_endpoint.username}
      password: ${database.postgres.write_endpoint.password}
