user:
  # Warning: These users can change content visibility!
  admin_emails:
    - "ben@bolte.cc"
    - "ben@dpsh.dev"
    - "bkbolte18@gmail.com"
  # For soft rollout, these users will be automatically approved, other users
  # will be waitlisted until an admin approves them. If this is removed, then
  # any user can sign up without being waitlisted.
  authorized_users: []
