name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build package
        uses: ./.github/actions/dpsh_build

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .mypy_cache
          key: dpsh-mypy-${{ env.pythonLocation }}-${{ github.event.pull_request.base.sha || github.sha }}
          restore-keys: |
            dpsh-mypy-${{ env.pythonLocation }}
            dpsh-mypy-

      - name: Run static checks
        run: |
          mkdir -p .mypy_cache
          make static-checks

      - name: Run unit tests
        run: |
          make test

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            .mypy_cache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
